jamesfer/cypher-query-builder

.travis.yml

Documentation wil now be rebuilt automatically on builds on the
master branch. It will be deployed to github when a release
occurs via the semantic-release script.

ci(docs): compile and deploy docs on ci builds

---

src/builder.ts

Documentation on what the override option did was inaccurate. Fixed errors and added more detailed
information about possible future deprecations.
Fixes #30

docs(Set): fix set's override option documentation

---

src/builder.ts
src/clauses/order-by.spec.ts
src/clauses/order-by.ts

This pull request adds a new constraint style for OrderBy. The existing one uses an object to specify properties, however, iteration order is not always guaranteed ([see this stackoverflow question](https://stackoverflow.com/questions/30076219/does-es6-introduce-a-well-defined-order-of-enumeration-for-object-properties)). While it is probably going to be consistent for many applications, it may not be for all. The existing object style will still be accepted but it may cause subtle bugs, so be aware.

New order by constraint style

---

package.json
src/clauses/set.spec.ts
src/clauses/set.ts
yarn.lock

When calling `.set` or `.setValues` with `override = false`, we now check that the value is an object before applying the `+=` operator. This fixes an issue that arose when trying to call `.setValues` with primitive values for each key.
```javascript
.setValues({
'card.title': card.title,
'card.type': card.type,
'card.isActive': card.isActive,
})
```
Fixes #39

Only use `+=` operator in Set clause when value is an object

---

src/clause.spec.ts
src/clause.ts

Previously when inlining variables, a simple string replacement was used which meant that shorter
variables could be inlined into longer ones. Eg. a variable "$param" could be inlined into the
string "$paramName" to produce 'value'Name, which is obviously incorrect. The string replacement
operation now attempts to only inline a param if it matches the entire variable.

fix(Clause): match whole variable when inlining using interpolate

---

src/clauses/where.spec.ts
src/clauses/where.ts

Previously, calling `build()` on a where clause would add more parameters each time. This side
effect has been moved so parameters are created in the constructor.
Closes #42

fix(Where): remove side effects from build

---

readme.md

Thanks for the great package! Just updating the ES versions for [`Promises`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Specifications) and [`async / await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#Specifications), easy to mix up.

 docs: correct ECMAScript versions in examples

---

src/clauses/where.spec.ts
src/clauses/where.ts

Previously, the combined where clause was created in the constructor and then reused later. This
meant that the parameter bag wouldn't be able to create a unique name for parameters in where
comparison functions because the where clause hadn't been attached to a query yet. This commit
changes this behaviour so that the where clause is created during the build call.

fix(Where): bind where clause parameters during build

---

src/clause.ts
src/parameter-container.ts
yarn.lock

Due to some functions not declaring their return types, typescript had to generate a long list of
`<reference path="...">` directives at the top of the declaration files. I think this was due to the
common "A member has or is using type from exported module that cannot be named" error.

fix: fix generated references to lodash types

---

rollup.config.js

fix: tell rollup to output external modules with node style paths

---

src/builder.ts
src/clauses/delete.spec.ts
src/clauses/delete.ts
tests/scenarios.test.ts

… detach
Previously the `delete` clause set the detach option to true, meaning that `.delete` and
`.detachDelete` actually had the same behaviour unless you explicitly set `detach: false` in the
delete options. It makes more sense for `delete` to become a `DELETE` clause in cypher and
`detachDelete` to become a `DETACH DELETE` clause.
BREAKING CHANGE: The `.delete` method now uses `detach: false` by default meaning that it will
become a plain old `DELETE` clause in cypher. To retain the previous behaviour of becoming a `DETACH
DELETE` clause by default, use the `.detachDelete` method instead.

fix(Delete): change the default behaviour of delete clause not to use DETACH DELETE

---

src/builder.ts
src/clauses/limit.ts
src/clauses/skip.ts

Change the type signature for both skip and limit to prevent them from accepting a string argument.
While passing in a string would still functionally work, it is probably a bug as argument only makes
sense with a numeric value.
BREAKING CHANGE: The type of skip and limit clauses no longer accept a string. This will only effect
typescript users, there is no breaking change for javascript users.

fix(Skip, Limit): make skip and limit only accept number amounts

---

src/builder.ts
src/clauses/where-comparators.ts
src/clauses/where-utils.ts
src/clauses/where.spec.ts

Javascript RegExp objects can now be passed into the regexp comparator and used directly as a value
in Where clauses.
Closes #13

feat(Where): allow RegExp objects directly in where clause

---

src/builder.ts
src/clauses/return.spec.ts
src/clauses/return.ts
tests/connection.test.ts

Return now supports an additional options parameter that contains a `distinct` flag. Setting it to
true will cause the return clause to only return unique rows. In addition, the `returnDistinct`
method was added to the query interface as a shortcut to `return(..., { distinct: true })`.
fix #90

Add distinct option to return clause

---

src/connection.ts
src/query.spec.ts
src/query.ts
tests/connection.test.ts

The run and stream methods on both the Connection and Query classes handled errors inconsistently,
sometimes throwing errors synchronously and sometimes returning rejected promises or observables.
This commit aims to make all of them consistent by always returning a promise or observable.
BREAKING CHANGE: The run and stream methods of the Connection and Query classes no longer throw
exceptions. Instead they return a rejected promise or an observable that will immediately error.
Fixes #93

Make error handling more consistent

---

src/clauses/index.ts
src/index.ts

Export some of the internal classes to make it easier to integrate and extend.
fix #116

Export builder, clause and clause collection

---

package.json
yarn.lock

All breaking dependencies could be updated without the need for a major release except for Neo4j, so I'm doing these separately.

Update breaking dependencies except neo4j

---

package.json
readme.md
src/connection.ts
src/query.ts
tests/connection.test.ts
yarn.lock

Removes the any-promise package. Maintaining support for it proved too much of a hassle for the
value it presented. Promises now have native support in Node and I believe there are better
solutions if you really want to use a different implementation. If you didn't use the
any-promise package then you shouldn't have to make any changes.
BREAKING CHANGE: Removes the any-promise package

Remove any-promise

---

package.json
readme.md
src/connection.ts
src/query.spec.ts
src/query.ts
tests/connection.test.ts
typings/any-observable/index.d.ts
yarn.lock

Removes the any-observable package. Maintaining support for it proved too much of a hassle for the value it presented. The RxJS library is quite obviously the defacto Observable library and the new Neo4j driver also uses RxJS observables.
BREAKING CHANGE: Removes the any-observable package

Remove any observable

---

docker/docker-compose.test.yml
src/transformer.ts

I am getting an error when a `Point` object comes in a query result when the `z` property is `undefined`.
[See here](https://github.com/neo4j/neo4j-javascript-driver/blob/4.0/types/spatial-types.d.ts#L27)
The error happens [here](https://github.com/bboure/cypher-query-builder/blob/e05ee0641af1bcbc9cbce1557911b9ede126499a/src/transformer.ts#L88) because:
- the `Point` value is [transformed recursively as an Object](https://github.com/bboure/cypher-query-builder/blob/e05ee0641af1bcbc9cbce1557911b9ede126499a/src/transformer.ts#L60)
- `isPlain()` returns false on `undefined`
- code reached `isRelation()` but `rel` is `undefined`.
- `undefined.identity` fails.
```js
TypeError: Cannot read property 'identity' of undefined
```
This is related to #122  since Spatial objects are not properly …

Handle undefined values in Transformer

---

src/builder.ts
src/clauses/term-list-clause.spec.ts
src/clauses/term-list-clause.ts
tests/utils.ts

The documentation described the behaviour of `with` and `return` when given a nested set of
dictionaries:
```javascript
query.with({
people: {
name: 'personName',
age: 'personAge',
},
});
// WITH people.name AS personName, people.age AS personAge
```
However the types forbade this. If using Javascript, no error was returned, however the
result was very different to the documentation. It now behaves as documentated.
If you are using Typescript this is not a breaking change as the types would have
prevented you from using the faulty behaviour.
If you as using Javascript then there is a chance that this will change the behaviour
of your code but it is unlikely and the other behaviour is a bug.
fixes #137

Fix handling of nested dictionaries

---

.npmignore

Hi,
I was investigating the size of my deployed packages that were getting quite big. 
In my investigation, I found out that this package is contributing to bloating my packages.
I identified two reasons:
1) Some `@types` packages sneaked into the prod dependencies, so they were installed even on prod (`npm install --only=prod`)
2) The Docs and all sorts of unnecessary files were included in the package published to npm making it 6.57 MB unpacked.
After removing, the unpacked size is down to about 1M

fix(Package): Reduce package size

---

.github/workflows/default.yml

Runs `yarn build` before releasing the bundle to npm. This was
step was forgotten when migrating the build to Github Actions.
fixes #173

Add missing build step before releasing
